name: apkmirror-dart
description: Server for APKmirror.com Android App
dependencies:
  browser: any
  http: ">=0.11.1+1 <0.12.0"
  shelf_route: ">=0.11.0 <0.12.0"
  shelf_bind: ">=0.7.0+1 <0.8.0"
  shelf_exception_response: '>=0.1.0 <0.2.0'
  xml: ">=1.0.0 <2.0.0"
  html5lib: any